# 인증 서버
server:
  port: 8090

###########
security:
  oauth2:
    client: #보통 OAuth2 인증을 지원하는 웹 사이트에서는 클라이언트 계정을 발급해줘 그 정보를 입력해야함, 여기서는 예제라서 임의로 하드코틷ㅇ
      client-id: n1tjrgns # client를 식별하는 고유 id
      client-secret: tistory # access token을 교환하기 위한 암호

    resource:
      jwt:
        key-value: jwt_secret_key

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/apigateway
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto:  create-drop #create 어플 실행시점에 자동 테이블 리셋모드
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect #hibernate.dialect' not set h2 에러 해결
        # show_sql: true #sysout 용
        format_sql: true